### ISSUE TITLE
checksums for medium and large.tar?

### ISSUE THREAD

**Issue by bmilde** [facebookresearch/libri-light#30]
Hi, 

for the larger downloads I get connection aborts from your server with wget very frequently, almost every 2 hours. Looks like this:

2020-01-16 22:34:56 (10.9 MB/s) - Connection closed at byte 811303997429. Retrying.

Wget is retrying, but I fear it happened so often now that something is corrupted. Could you please release checksums (md5/sha or something like it)? Thank you and also many thanks for releasing this exciting dataset!

**Comment by lunixbochs** [comment]
c49207eb86a8e8ac895561c37232041e  small.tar
c75e7ac62471bfbf2db77528d62a9b74  medium.tar

I'll let you know when large finishes summing, it will take a while.

**Comment by jacobkahn** [comment]
@lunixbochs sums agree with mine - thanks for running those. I'm going to add them to readme as well for posterity.
