### ISSUE TITLE
ABX eval script $FEATURE_SIZE

### ISSUE THREAD

**Issue by bmilde** [facebookresearch/libri-light#36]
In the eval README it says "$FEATURE_SIZE is the duration (in s) of one feature of the model (for a 10ms frame rate, this would be 0.01)."

When I try use 0.01 as feature size I get:

usage: eval_ABX.py [-h] [--path_checkpoint PATH_CHECKPOINT]
                   [--file_extension {.pt,.npy,.wav,.flac,.mp3}]
                   [--feature_size FEATURE_SIZE] [--cuda]
                   [--mode {all,within,across}]
                   [--distance_mode {euclidian,cosine}]
                   [--max_size_group MAX_SIZE_GROUP]
                   [--max_x_across MAX_X_ACROSS] [--out OUT]
                   path_data path_item_file
eval_ABX.py: error: argument --feature_size: invalid int value: '0.01'

Oddly enough the default is also 0.01, but the type is int in the parse argument:

    parser.add_argument('--feature_size', type=int, default=0.01,
                        help="Size (in s) of one feature")

I assume it should be type=float? Or does feature_size mean something else?

**Comment by Molugan** [comment]
Hello,

Indeed it seems that it should be a float ! Sorry about that, we worked with the default value in our test and missed the bug. I'll add a PR soon to fix the bug.
