### ISSUE TITLE
Feature request: KL-divergence in ABX computations

### ISSUE THREAD

**Issue by bmilde** [facebookresearch/libri-light#37]
Can you add KL-divergence as a distance metric to the ABX eval? This usually needed/used to compare pseudo-posteriorgrams. Thank you!

**Comment by bmilde** [comment]
I've implemented KL-Divergence and symmetric KL in ABX_src/abx_group_computation.py, will do a pull request soon! Also gives better results on my posteriorgrams than cosine/euclidean.

**Comment by bmilde** [comment]
https://github.com/facebookresearch/libri-light/pull/39

**Comment by eugene-kharitonov** [comment]
Hello @bmilde , as I understand this was solved with https://github.com/facebookresearch/libri-light/pull/39 ? Can I close the issue? Thanks!

**Comment by bmilde** [comment]
Yes it can be closed!
