### ISSUE TITLE
Sampling rate?

### ISSUE THREAD

**Issue by aqibsaeed** [facebookresearch/libri-light#45]
Hi,

What's the sampling rate of raw data? 16kHz?

**Comment by aqibsaeed** [comment]
What it be ok to convert the `flac` to `wav` as follows: `ffmpeg -i <fn>.flac -ac 1 -ar 16000 <output_fn>.wav` ? Thanks.

**Comment by aqibsaeed** [comment]
Hi @jacobkahn, would you please look into this?

**Comment by jacobkahn** [comment]
@aqibsaeed — yes, the sampling rate is 16 kHz. In theory, converting to 16kHz wav should be fine.
