### ISSUE TITLE
ABX_src setup issues

### ISSUE THREAD

**Issue by Lazypanda278** [facebookresearch/libri-light#46]
I'm trying to use the eval module.  
When I run :
python setup.py build_ext --inplace

I get the following error : 

Compiling dtw.pyx because it depends on /home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/Cython/Includes/libc/string.pxd.
[1/1] Cythonizing dtw.pyx
/home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /mnt/efs/data/libri-light/eval/ABX_src/dtw.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running build_ext
building 'ABX_src.dtw' extension
gcc -pthread -B /home/ubuntu/anaconda3/envs/libri-light/compiler_compat -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -fPIC -O2 -isystem /home/ubuntu/anaconda3/envs/libri-light/include -fPIC -O2 -isystem /home/ubuntu/anaconda3/envs/libri-light/include -fPIC -I/home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/numpy/core/include -I/home/ubuntu/anaconda3/envs/libri-light/include/python3.10 -c dtw.c -o build/temp.linux-x86_64-3.10/dtw.o
In file included from /home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:0,
                 from /home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from dtw.c:711:
/home/ubuntu/anaconda3/envs/libri-light/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^~~~~~~
gcc -pthread -B /home/ubuntu/anaconda3/envs/libri-light/compiler_compat -shared -Wl,-rpath,/home/ubuntu/anaconda3/envs/libri-light/lib -Wl,-rpath-link,/home/ubuntu/anaconda3/envs/libri-light/lib -L/home/ubuntu/anaconda3/envs/libri-light/lib -Wl,-rpath,/home/ubuntu/anaconda3/envs/libri-light/lib -Wl,-rpath-link,/home/ubuntu/anaconda3/envs/libri-light/lib -L/home/ubuntu/anaconda3/envs/libri-light/lib build/temp.linux-x86_64-3.10/dtw.o -o build/lib.linux-x86_64-3.10/ABX_src/dtw.cpython-310-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.10/ABX_src/dtw.cpython-310-x86_64-linux-gnu.so -> ABX_src
error: could not create 'ABX_src/dtw.cpython-310-x86_64-linux-gnu.so': No such file or directory

Not sure why this is happening. Any help will be highly appreciated. Thanks in advance.

**Comment by jacobkahn** [comment]
Per the compile warning, you should probably install an older version of numpy.

cc @Molugan, @eugene-kharitonov

**Comment by Lazypanda278** [comment]
Hey everyone. Thanks for the replies. 

I believe it was an issue with the x86_64-linux-gnu-gcc. I was able to solve it by reinstalling python-dev.

**Comment by XiaoyuBIE1994** [comment]
FYI, for those who has this problem and can't try to re-install python-dev (on the cluster for example), you can try to create a directory `ABX_src` inside `eval/ABX_src` (i.e. eval/ABX_src/ABX_src). This works for me to tackle this error.
